/**
 * Generate Word Frequency Scores
 *
 * Reads real Lexique 3 frequency data from data/lexique3-top10k.csv,
 * looks up each game word, and generates src/lib/word-frequencies.ts
 * with normalized scores (0 = very common, 1 = very rare).
 *
 * Usage: npx tsx scripts/generate-word-frequencies.ts
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { normalizeForLookup } from '../src/lib/normalize';
import { parseWordsCsv } from './parse-words-csv';

const PROJECT_ROOT = path.resolve(__dirname, '..');
const CSV_PATH = path.join(PROJECT_ROOT, 'data/lexique3-top10k.csv');
const OUTPUT_PATH = path.join(PROJECT_ROOT, 'src/lib/word-frequencies.ts');

const normalize = normalizeForLookup;

function main() {
  // 1. Read CSV
  const csvContent = fs.readFileSync(CSV_PATH, 'utf-8');
  const lines = csvContent.trim().split('\n').slice(1); // skip header

  const freqMap = new Map<string, number>();
  let maxFreq = 0;

  for (const line of lines) {
    const lastComma = line.lastIndexOf(',');
    if (lastComma === -1) continue;
    const word = line.slice(0, lastComma).trim();
    const freq = parseFloat(line.slice(lastComma + 1).trim());
    if (isNaN(freq)) continue;

    const key = normalize(word);
    // Keep highest frequency if duplicates
    if (!freqMap.has(key) || freq > freqMap.get(key)!) {
      freqMap.set(key, freq);
    }
    if (freq > maxFreq) maxFreq = freq;
  }

  console.log(`Loaded ${freqMap.size} words from CSV (maxFreq=${maxFreq})`);

  // 2. Read game words from CSV
  const gameWords = parseWordsCsv(PROJECT_ROOT).map((e) => e.word);

  console.log(`Found ${gameWords.length} game words`);

  // 3. Compute scores
  // Use percentile-based ranking: score reflects position in frequency distribution
  // Higher frequency → lower score (more common), lower frequency → higher score (rarer)
  const DEFAULT_UNKNOWN_SCORE = 0.8;
  const entries: [string, number][] = [];
  let missing = 0;

  // Collect frequencies for all game words first
  const gameFreqs: { key: string; word: string; freq: number }[] = [];
  for (const word of gameWords) {
    const key = normalize(word);
    const freq = freqMap.get(key);
    if (freq !== undefined) {
      gameFreqs.push({ key, word, freq });
    } else {
      missing++;
      console.warn(`  WARNING: "${word}" not found in CSV, using default ${DEFAULT_UNKNOWN_SCORE}`);
      entries.push([key, DEFAULT_UNKNOWN_SCORE]);
    }
  }

  // Sort by frequency descending, assign scores based on rank
  // But also use the actual frequency values with log scale relative to corpus
  // Use log scale with a reference max of 200 (approx highest game word freq)
  // to spread scores well across [0, 0.79] range
  const refMax = 200; // roughly the highest freq among game words (France=180)
  const logRef = Math.log(refMax + 1);

  for (const { key, freq } of gameFreqs) {
    // Map freq to [0, ~0.79] using log scale
    // score = 0.79 * (1 - log(freq+1) / log(refMax+1))
    const score = 0.79 * (1 - Math.log(freq + 1) / logRef);
    const clamped = Math.max(0, Math.min(0.79, score));
    entries.push([key, Math.round(clamped * 100) / 100]);
  }

  if (missing > 0) {
    console.warn(`${missing} words not found in frequency data`);
  }

  // 4. Generate output
  const mapEntries = entries.map(([word, score]) => `  ['${word}', ${score}],`).join('\n');

  const output = `/**
 * Word Frequency Scores — GENERATED FILE
 *
 * DO NOT EDIT MANUALLY.
 * Generated by: npx tsx scripts/generate-word-frequencies.ts
 * Source: data/lexique3-top10k.csv (Lexique 3 freqlivres)
 *
 * Maps French words to a frequency score (0 = very common, 1 = very rare).
 */

import { normalizeForLookup } from './normalize';

const DEFAULT_UNKNOWN_SCORE = 0.8;

/** Word frequency scores: normalized word → score (0-1) */
export const WORD_FREQUENCY_SCORES: ReadonlyMap<string, number> = new Map([
${mapEntries}
]);

/**
 * Get frequency score for a word (0 = very common, 1 = very rare).
 * Case-insensitive, accent-insensitive lookup via shared normalize utility.
 */
export function getWordFrequencyScore(word: string): number {
  return WORD_FREQUENCY_SCORES.get(normalizeForLookup(word)) ?? DEFAULT_UNKNOWN_SCORE;
}
`;

  fs.writeFileSync(OUTPUT_PATH, output, 'utf-8');
  console.log(`\nGenerated ${OUTPUT_PATH}`);
  console.log(`  ${entries.length} words with frequency scores`);

  // Print some key words for verification
  const keyWords = ['chat', 'kiwi', 'pomme', 'hippopotame', 'france', 'paris'];
  console.log('\nKey word frequencies:');
  for (const w of keyWords) {
    const key = normalize(w);
    const freq = freqMap.get(key);
    const entry = entries.find(([k]) => k === key);
    console.log(`  ${w}: freq=${freq ?? 'N/A'}/M, score=${entry?.[1] ?? 'N/A'}`);
  }
}

main();
