/**
 * Generate Word Classifications
 *
 * Reads words from src/lib/words.ts, computes composite difficulty
 * scores, and generates src/lib/word-classifications.ts.
 *
 * Usage: npx tsx scripts/generate-word-classifications.ts
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { computeSourceHash } from './source-hash';

const PROJECT_ROOT = path.resolve(__dirname, '..');

interface WordClassification {
  word: string;
  category: string;
  difficulty: string;
  letterCount: number;
}

async function main() {
  // Dynamic imports
  const { WORDS } = await import('../src/lib/words');
  const { computeDifficultyScore } = await import('../src/lib/difficulty-scorer');
  const { normalizeWord } = await import('../src/lib/normalize');

  const classifications: WordClassification[] = WORDS.map(
    (entry: { word: string; category: string }) => {
      const score = computeDifficultyScore(entry.word);
      const normalized = normalizeWord(entry.word);
      return {
        word: entry.word,
        category: entry.category,
        difficulty: score.level,
        letterCount: normalized.length,
      };
    }
  );

  const stats = { easy: 0, normal: 0, hard: 0 };
  for (const c of classifications) {
    stats[c.difficulty as keyof typeof stats]++;
  }

  const sourceHash = computeSourceHash(PROJECT_ROOT);
  const total = classifications.length;

  const output = `/**
 * Word Classifications — GENERATED FILE
 *
 * DO NOT EDIT MANUALLY.
 * Generated by: npx tsx scripts/generate-word-classifications.ts
 * Source hash: ${sourceHash}
 *
 * Distribution: easy=${stats.easy} (${Math.round((stats.easy / total) * 100)}%), normal=${stats.normal} (${Math.round((stats.normal / total) * 100)}%), hard=${stats.hard} (${Math.round((stats.hard / total) * 100)}%)
 * Total words: ${total}
 */

import type { DifficultyLevel } from '@/types/difficulty';

/** Source hash for freshness validation */
export const SOURCE_HASH = '${sourceHash}';

/** Pre-classified word entry */
export interface ClassifiedWordEntry {
  word: string;
  category: string;
  difficulty: DifficultyLevel;
  letterCount: number;
}

/** Pre-computed word classifications */
export const WORD_CLASSIFICATIONS: readonly ClassifiedWordEntry[] = ${JSON.stringify(classifications, null, 2)};
`;

  const outputPath = path.join(PROJECT_ROOT, 'src/lib/word-classifications.ts');
  fs.writeFileSync(outputPath, output, 'utf-8');

  console.log(`Generated ${outputPath}`);
  console.log(`  Total words: ${total}`);
  console.log(`  Easy: ${stats.easy} (${Math.round((stats.easy / total) * 100)}%)`);
  console.log(`  Normal: ${stats.normal} (${Math.round((stats.normal / total) * 100)}%)`);
  console.log(`  Hard: ${stats.hard} (${Math.round((stats.hard / total) * 100)}%)`);
  console.log(`  Source hash: ${sourceHash}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
